In [3]:
import numpy as np


## EXERCICE 1

In [4]:
# Question 1 : construire un tableau numpy

np.array([1,5,7,8])


array([1, 5, 7, 8])

In [5]:
# 2 : construire un tableau numpy

np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#3 : un tableau de 10 elements de 0

c=np.zeros(10)
c

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
# 4 : un tableau de 2 lignes et 5 colonnes rempli de 0

np.zeros([2,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
# 5 : un tableau de 10 elements rempli de 1

np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
# 6 : un tableau de 2 lignes et 5 colonnes rempli de 1

np.ones([2,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
# 7 : un tableau de 10 elements rempli de 8.5

np.full((10),8.5)

array([8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5])

In [11]:
# 8 : tableau de serie entiers sucessifs allant de 1 a 9 inclus

np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# 9 : tableau de 3 liges et 3 colonnes de serie entiers sucessifs allant de 1 a 9 inclus

np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
# 10 : creer une matrice identite de 4 lignes et 4 colonnes

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
# 11 : tableau rempli de valeurs aleatoires normales centrees en 0 

np.linspace(-5,5,5)



array([-5. , -2.5,  0. ,  2.5,  5. ])

In [15]:
# 12 : tableau rempli de valeurs aleatoires entieres comprises entre 1 et 10

a=np.random.randint(1,10,20)
a

array([2, 3, 6, 8, 9, 3, 9, 4, 6, 9, 4, 1, 4, 6, 1, 5, 6, 2, 6, 2])

In [41]:
# 13 : transformer le tableau en matrice de 4 lignes et 5 colonnes

np.reshape(a,(4,5))

array([[2, 2, 2, 9, 8],
       [5, 6, 6, 2, 6],
       [1, 5, 7, 2, 2],
       [9, 4, 9, 4, 8]])

In [43]:
# 14 : tableau de 5 elements compris entre 0 et 1 avec une amplitude egale

np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## EXERCIE 2

In [53]:
#EXERCIE 2 
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
#1 : afficher le nombre de lignes  et de colonnes

a.shape

(3, 3)

In [52]:
#2 : afficher la dimension du tableau

a.ndim

2

In [56]:
#3 : afficher le nombre d'elements du tableau

a.size

9

In [157]:
#4 : afficher le type des elements du tableau

print(a.dtype)

int32


## EXERCICE 3

In [58]:
# EXERCIE 3
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
#1 :afficher la valeur 5 qu est dans la tableau

a[1,1]

5

In [65]:
#2 : remplacer le 5 qui est dans le tableau par 0

a[1,1]=0
a
#a[a==5]=0

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [60]:
#3 : afficher les chiffres 3,6 et 9 du tableau 9

a[0:3,2]

array([3, 6, 9])

In [158]:
#4 :  tableau de 4 lignes et 3 colonnes de 12 nombres aleatoires copmris entre 0 et 9

b=np.random.randint(1,9,(4,3))
b

array([[6, 4, 4],
       [8, 3, 4],
       [1, 1, 1],
       [8, 8, 5]])

In [81]:
#5 : verifier s'il ya des nombres inferieures a 5

b<5

array([[ True, False, False],
       [ True, False,  True],
       [ True,  True,  True],
       [False, False, False]])

In [88]:
#6 : remplacer les nombres inf a 5 par 0

b[b<5]=0
b

array([[0, 6, 5],
       [0, 5, 0],
       [0, 0, 0],
       [7, 5, 6]])

## EXERCICE 4

In [68]:
#1 : creer un tableau de 11 elements de nombres alea compris entre 0 et 9

a=np.random.randint(0,9,11)
a

array([0, 8, 2, 7, 3, 3, 1, 5, 1, 0, 1])

In [69]:
#2 : type des elements du tableau 

a.dtype

dtype('int32')

In [70]:
# 3 : changer le type des elements du tableau

z=a.astype('float32')
z.dtype

dtype('float32')

In [71]:
#4 : ajouter le chiffre 3 a la fin du tableau a 1 dimension

a=np.append(a,3)
a

array([0, 8, 2, 7, 3, 3, 1, 5, 1, 0, 1, 3])

In [72]:
#5 : Tranformer le tableau a en une matrice de 3 lignes 4 colonnes

a=a.reshape(3,4)
a


array([[0, 8, 2, 7],
       [3, 3, 1, 5],
       [1, 0, 1, 3]])

In [73]:
#6 : matrice de 3 lignes 4 colonnes de serie entiers sucessifs allant de 1 a 12 inclus

b=np.arange(1,13).reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [74]:
#7 : matrice c concatenation de a et b dans le sens horizontal

#c=np.concatenate((a,b),axis=1)
c= np.hstack((a,b))
c

array([[ 0,  8,  2,  7,  1,  2,  3,  4],
       [ 3,  3,  1,  5,  5,  6,  7,  8],
       [ 1,  0,  1,  3,  9, 10, 11, 12]])

In [75]:
#8 :  matrice c concatenation de a et b dans le sens vertical

#d=np.concatenate((a,b),axis=0)
d=np.vstack((a,b))
d

array([[ 0,  8,  2,  7],
       [ 3,  3,  1,  5],
       [ 1,  0,  1,  3],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [78]:
#9 : aplatir le tableau d

#d.ravel()
#d.reshape(-1)
d.flatten()

array([ 0,  8,  2,  7,  3,  3,  1,  5,  1,  0,  1,  3,  1,  2,  3,  4,  5,
        6,  7,  8,  9, 10, 11, 12])

In [41]:
# 10 : supprimer  dernier element du tableau

np.delete(d,-1)

array([ 0,  3,  3,  2,  7,  0,  4,  1,  8,  8,  8,  3,  1,  2,  3,  4,  5,
        6,  7,  8,  9, 10, 11])

## EXERCICE :STATISTIQUE AVEC NUMPY

In [46]:
# EXERCICE : STATISTIQUE AVEC NUMPY

a= np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
#1 : afficher la somme des elements du tableau

np.sum(a)

45

In [146]:
#2 : afficher la somme des elements du tableau par colonne

np.sum(a,axis=0)

array([12, 15, 18])

In [147]:
#3 : afficher la somme des elements du tableau par ligne

np.sum(a,axis=1)

array([ 6, 15, 24])

In [149]:
#4 : afficher le produit des elements par colonne

np.prod(a,axis=0)

array([ 28,  80, 162])

In [150]:
#5 : afficher le minimum des elements du tableau

np.min(a)

1

In [151]:
#6 : afficher le maximum des elements du tableau

np.max(a)

9

In [152]:
#7 : afficher la   moyenne des elements du tableau

np.mean(a)

5.0

In [153]:
#8 : afficher la variance

np.var(a)

6.666666666666667

In [154]:
#9 :afficher l'ecart type                 

np.std(a)

2.581988897471611

In [55]:
np.random.n()

2.9003008511450488